spring:
  application:
    name: activityservice

  data:
    mongodb:
      uri: mongodb://localhost:27017/aiactivityfitness
      database: aiactivityfitness

eureka:
  client:
    serviceUrl:
      defaultZone: https://localhost8761/eureka/

server:
  port: 8082


spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
